version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:30"
    open-pull-requests-limit: 5
    groups:
      github-actions-group:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"